# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jpmobile}
  s.version = "3.0.5"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yoji Shidara", "Shin-ichiro OGAWA"]
  s.date = %q{2011-01-28}
  s.description = %q{A Rails plugin for Japanese mobile-phones}
  s.email = %q{dara@shidara.net}
  s.extra_rdoc_files = [
    "README",
    "README.rdoc"
  ]
  s.files = Dir['CHANGELOG', 'MIT-LICENSE', 'README', 'README.rdoc', 'init.rb', 'install.rb', 'lib/**/*.*', 'tools/**/*.*']
  s.homepage = %q{http://jpmobile-rails.org}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Rails plugin for Japanese mobile-phones}
  s.test_files = Dir['spec/**/*.*', 'test/**/"."' 'tmp/**/*.*']

  s.add_development_dependency(%q<jeweler>, [">= 0"])
  s.add_development_dependency(%q<rails>, [">= 3.2.8"])
  s.add_development_dependency(%q<rspec>, [">= 2.3.0"])
  s.add_development_dependency(%q<rspec-rails>, [">= 2.3.0"])
  s.add_development_dependency(%q<webrat>, [">= 0"])
  s.add_development_dependency(%q<geokit>, [">= 0"])
  s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
  s.add_development_dependency(%q<hpricot>, [">= 0"])
  s.add_development_dependency(%q<jeweler>, [">= 1.5.1"])
  s.add_development_dependency(%q<rspec>, [">= 2.3.0"])
  s.add_development_dependency(%q<rspec-rails>, [">= 2.3.0"])
  s.add_development_dependency(%q<webrat>, [">= 0.7.2"])
  s.add_development_dependency(%q<geokit>, [">= 1.5.0"])
  s.add_development_dependency(%q<sqlite3-ruby>, [">= 1.3.2"])
  s.add_development_dependency(%q<hpricot>, [">= 0.8.3"])
  s.add_development_dependency(%q<git>, [">= 1.2.5"])
  s.add_development_dependency(%q<rails>, [">= 3.0.3"])
end
