# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{jpmobile}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Yoji Shidara", "Shin-ichiro OGAWA"]
  s.date = %q{2010-12-17}
  s.description = %q{A Rails plugin for Japanese mobile-phones}
  s.email = %q{dara@shidara.net}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG",
    "Gemfile",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "init.rb",
    "install.rb",
    "lib/jpmobile.rb",
    "lib/jpmobile/datum_conv.rb",
    "lib/jpmobile/docomo_guid.rb",
    "lib/jpmobile/email.rb",
    "lib/jpmobile/emoticon.rb",
    "lib/jpmobile/emoticon/au.rb",
    "lib/jpmobile/emoticon/conversion_table.rb",
    "lib/jpmobile/emoticon/docomo.rb",
    "lib/jpmobile/emoticon/softbank.rb",
    "lib/jpmobile/emoticon/z_combine.rb",
    "lib/jpmobile/encoding.rb",
    "lib/jpmobile/filter.rb",
    "lib/jpmobile/helpers.rb",
    "lib/jpmobile/hook_action_controller.rb",
    "lib/jpmobile/hook_action_view.rb",
    "lib/jpmobile/mobile/abstract_mobile.rb",
    "lib/jpmobile/mobile/android.rb",
    "lib/jpmobile/mobile/au.rb",
    "lib/jpmobile/mobile/ddipocket.rb",
    "lib/jpmobile/mobile/docomo.rb",
    "lib/jpmobile/mobile/emobile.rb",
    "lib/jpmobile/mobile/iphone.rb",
    "lib/jpmobile/mobile/smart_phone.rb",
    "lib/jpmobile/mobile/softbank.rb",
    "lib/jpmobile/mobile/vodafone.rb",
    "lib/jpmobile/mobile/willcom.rb",
    "lib/jpmobile/mobile/windows_phone.rb",
    "lib/jpmobile/position.rb",
    "lib/jpmobile/rack.rb",
    "lib/jpmobile/rack/filter.rb",
    "lib/jpmobile/rack/mobile_carrier.rb",
    "lib/jpmobile/rack/params_filter.rb",
    "lib/jpmobile/rails.rb",
    "lib/jpmobile/request_with_mobile.rb",
    "lib/jpmobile/trans_sid.rb",
    "lib/jpmobile/util.rb",
    "lib/tasks/jpmobile_tasks.rake",
    "tools/emoji/genregexp.rb",
    "tools/generate_au_emoticon_table.rb",
    "tools/generate_docomo_emoticon_table.rb",
    "tools/generate_emoticon_conversion_table.rb",
    "tools/generate_softbank_emoticon_table.rb",
    "tools/list_gps_unsupported_au.rb"
  ]
  s.homepage = %q{http://jpmobile-rails.org}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Rails plugin for Japanese mobile-phones}
  s.test_files = [
    "spec/rack/jpmobile/android_spec.rb",
    "spec/rack/jpmobile/au_spec.rb",
    "spec/rack/jpmobile/docomo_spec.rb",
    "spec/rack/jpmobile/emoticon_spec.rb",
    "spec/rack/jpmobile/filter_spec.rb",
    "spec/rack/jpmobile/iphone_spec.rb",
    "spec/rack/jpmobile/mobile_by_ua_spec.rb",
    "spec/rack/jpmobile/params_filter_spec.rb",
    "spec/rack/jpmobile/softbank_spec.rb",
    "spec/rack/jpmobile/willcom_spec.rb",
    "spec/rack/jpmobile/windows_phone.rb",
    "spec/rack_helper.rb",
    "spec/spec_helper.rb",
    "spec/unit/detect_by_email_spec.rb",
    "spec/unit/is_carrier_spec.rb",
    "spec/unit/spec_helper.rb",
    "spec/unit/util_spec.rb",
    "spec/unit/valid_ip_spec.rb",
    "test/legacy/emoticon_test.rb",
    "test/legacy/helper.rb",
    "test/rails/overrides/app/controllers/application_controller.rb",
    "test/rails/overrides/app/controllers/docomo_guid_always_controller.rb",
    "test/rails/overrides/app/controllers/docomo_guid_base_controller.rb",
    "test/rails/overrides/app/controllers/docomo_guid_docomo_controller.rb",
    "test/rails/overrides/app/controllers/filter_controller.rb",
    "test/rails/overrides/app/controllers/filter_controller_base.rb",
    "test/rails/overrides/app/controllers/hankaku_filter_controller.rb",
    "test/rails/overrides/app/controllers/hankaku_input_filter_controller.rb",
    "test/rails/overrides/app/controllers/links_controller.rb",
    "test/rails/overrides/app/controllers/mobile_spec_controller.rb",
    "test/rails/overrides/app/controllers/template_path_controller.rb",
    "test/rails/overrides/app/controllers/trans_sid_always_and_session_off_controller.rb",
    "test/rails/overrides/app/controllers/trans_sid_always_controller.rb",
    "test/rails/overrides/app/controllers/trans_sid_base_controller.rb",
    "test/rails/overrides/app/controllers/trans_sid_metal_controller.rb",
    "test/rails/overrides/app/controllers/trans_sid_mobile_controller.rb",
    "test/rails/overrides/app/controllers/trans_sid_none_controller.rb",
    "test/rails/overrides/app/models/user.rb",
    "test/rails/overrides/autotest/discover.rb",
    "test/rails/overrides/config/initializers/jpmobile_generator.rb",
    "test/rails/overrides/config/routes.rb",
    "test/rails/overrides/db/migrate/001_add_sessions_table.rb",
    "test/rails/overrides/db/migrate/20100824062306_create_users.rb",
    "test/rails/overrides/spec/helpers/helpers_spec.rb",
    "test/rails/overrides/spec/requests/docomo_guid_spec.rb",
    "test/rails/overrides/spec/requests/docomo_spec.rb",
    "test/rails/overrides/spec/requests/emobile_spec.rb",
    "test/rails/overrides/spec/requests/filter_spec.rb",
    "test/rails/overrides/spec/requests/helpers_spec.rb",
    "test/rails/overrides/spec/requests/pc_spec.rb",
    "test/rails/overrides/spec/requests/softbank_emulator_spec.rb",
    "test/rails/overrides/spec/requests/template_path_spec.rb",
    "test/rails/overrides/spec/requests/trans_sid_spec.rb",
    "test/rails/overrides/spec/spec_helper.rb",
    "test/rails/rails_root/app/controllers/application_controller.rb",
    "test/rails/rails_root/app/controllers/docomo_guid_always_controller.rb",
    "test/rails/rails_root/app/controllers/docomo_guid_base_controller.rb",
    "test/rails/rails_root/app/controllers/docomo_guid_docomo_controller.rb",
    "test/rails/rails_root/app/controllers/filter_controller.rb",
    "test/rails/rails_root/app/controllers/filter_controller_base.rb",
    "test/rails/rails_root/app/controllers/hankaku_filter_controller.rb",
    "test/rails/rails_root/app/controllers/hankaku_input_filter_controller.rb",
    "test/rails/rails_root/app/controllers/links_controller.rb",
    "test/rails/rails_root/app/controllers/mobile_spec_controller.rb",
    "test/rails/rails_root/app/controllers/template_path_controller.rb",
    "test/rails/rails_root/app/controllers/trans_sid_always_and_session_off_controller.rb",
    "test/rails/rails_root/app/controllers/trans_sid_always_controller.rb",
    "test/rails/rails_root/app/controllers/trans_sid_base_controller.rb",
    "test/rails/rails_root/app/controllers/trans_sid_metal_controller.rb",
    "test/rails/rails_root/app/controllers/trans_sid_mobile_controller.rb",
    "test/rails/rails_root/app/controllers/trans_sid_none_controller.rb",
    "test/rails/rails_root/app/helpers/application_helper.rb",
    "test/rails/rails_root/app/models/user.rb",
    "test/rails/rails_root/autotest/discover.rb",
    "test/rails/rails_root/config/application.rb",
    "test/rails/rails_root/config/boot.rb",
    "test/rails/rails_root/config/environment.rb",
    "test/rails/rails_root/config/environments/development.rb",
    "test/rails/rails_root/config/environments/production.rb",
    "test/rails/rails_root/config/environments/test.rb",
    "test/rails/rails_root/config/initializers/backtrace_silencers.rb",
    "test/rails/rails_root/config/initializers/inflections.rb",
    "test/rails/rails_root/config/initializers/jpmobile_generator.rb",
    "test/rails/rails_root/config/initializers/mime_types.rb",
    "test/rails/rails_root/config/initializers/secret_token.rb",
    "test/rails/rails_root/config/initializers/session_store.rb",
    "test/rails/rails_root/config/routes.rb",
    "test/rails/rails_root/db/migrate/001_add_sessions_table.rb",
    "test/rails/rails_root/db/migrate/20100824062306_create_users.rb",
    "test/rails/rails_root/db/schema.rb",
    "test/rails/rails_root/db/seeds.rb",
    "test/rails/rails_root/spec/helpers/helpers_spec.rb",
    "test/rails/rails_root/spec/requests/docomo_guid_spec.rb",
    "test/rails/rails_root/spec/requests/docomo_spec.rb",
    "test/rails/rails_root/spec/requests/emobile_spec.rb",
    "test/rails/rails_root/spec/requests/filter_spec.rb",
    "test/rails/rails_root/spec/requests/helpers_spec.rb",
    "test/rails/rails_root/spec/requests/pc_spec.rb",
    "test/rails/rails_root/spec/requests/softbank_emulator_spec.rb",
    "test/rails/rails_root/spec/requests/template_path_spec.rb",
    "test/rails/rails_root/spec/requests/trans_sid_spec.rb",
    "test/rails/rails_root/spec/spec_helper.rb",
    "test/rails/rails_root/test/performance/browsing_test.rb",
    "test/rails/rails_root/test/test_helper.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-ipaddresses/lib/jpmobile-ipaddresses.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/abstract_ip_addresses.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/au.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/docomo.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/emobile.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/softbank.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/willcom.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-terminfo/lib/jpmobile-terminfo.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-terminfo/lib/jpmobile/mobile/terminfo.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-terminfo/lib/jpmobile/mobile/terminfo/docomo.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-terminfo/spec/spec_helper.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile-terminfo/spec/terminfo_spec.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/init.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/install.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/datum_conv.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/docomo_guid.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/email.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/emoticon.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/emoticon/au.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/emoticon/conversion_table.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/emoticon/docomo.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/emoticon/softbank.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/emoticon/z_combine.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/encoding.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/filter.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/helpers.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/hook_action_controller.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/hook_action_view.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/abstract_mobile.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/android.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/au.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/ddipocket.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/docomo.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/emobile.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/iphone.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/smart_phone.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/softbank.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/vodafone.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/willcom.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/mobile/windows_phone.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/position.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/rack.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/rack/filter.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/rack/mobile_carrier.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/rack/params_filter.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/rails.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/request_with_mobile.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/trans_sid.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/lib/jpmobile/util.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/tmp/conversion-table.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/tmp/utf8_to_image.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/tools/emoji/genregexp.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/tools/generate_au_emoticon_table.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/tools/generate_docomo_emoticon_table.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/tools/generate_emoticon_conversion_table.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/tools/generate_softbank_emoticon_table.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/tools/list_gps_unsupported_au.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-ipaddresses/lib/jpmobile-ipaddresses.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/abstract_ip_addresses.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/au.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/docomo.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/emobile.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/softbank.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-ipaddresses/lib/jpmobile/mobile/ip_addresses/willcom.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-terminfo/lib/jpmobile-terminfo.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-terminfo/lib/jpmobile/mobile/terminfo.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-terminfo/lib/jpmobile/mobile/terminfo/docomo.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-terminfo/spec/spec_helper.rb",
    "test/rails/rails_root/vendor/plugins/jpmobile/vendor/jpmobile-terminfo/spec/terminfo_spec.rb",
    "test/sinatra/guestbook.rb",
    "test/sinatra/test/filter_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rails>, [">= 3.0.3"])
      s.add_development_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.3.0"])
      s.add_development_dependency(%q<webrat>, [">= 0"])
      s.add_development_dependency(%q<geokit>, [">= 0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_development_dependency(%q<hpricot>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.5.1"])
      s.add_development_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 2.3.0"])
      s.add_development_dependency(%q<webrat>, [">= 0.7.2"])
      s.add_development_dependency(%q<geokit>, [">= 1.5.0"])
      s.add_development_dependency(%q<sqlite3-ruby>, [">= 1.3.2"])
      s.add_development_dependency(%q<hpricot>, [">= 0.8.3"])
      s.add_development_dependency(%q<git>, [">= 1.2.5"])
      s.add_development_dependency(%q<rails>, [">= 3.0.3"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 3.0.3"])
      s.add_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.3.0"])
      s.add_dependency(%q<webrat>, [">= 0"])
      s.add_dependency(%q<geokit>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<hpricot>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 1.5.1"])
      s.add_dependency(%q<rspec>, [">= 2.3.0"])
      s.add_dependency(%q<rspec-rails>, [">= 2.3.0"])
      s.add_dependency(%q<webrat>, [">= 0.7.2"])
      s.add_dependency(%q<geokit>, [">= 1.5.0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 1.3.2"])
      s.add_dependency(%q<hpricot>, [">= 0.8.3"])
      s.add_dependency(%q<git>, [">= 1.2.5"])
      s.add_dependency(%q<rails>, [">= 3.0.3"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 3.0.3"])
    s.add_dependency(%q<rspec>, [">= 2.3.0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.3.0"])
    s.add_dependency(%q<webrat>, [">= 0"])
    s.add_dependency(%q<geokit>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<hpricot>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 1.5.1"])
    s.add_dependency(%q<rspec>, [">= 2.3.0"])
    s.add_dependency(%q<rspec-rails>, [">= 2.3.0"])
    s.add_dependency(%q<webrat>, [">= 0.7.2"])
    s.add_dependency(%q<geokit>, [">= 1.5.0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 1.3.2"])
    s.add_dependency(%q<hpricot>, [">= 0.8.3"])
    s.add_dependency(%q<git>, [">= 1.2.5"])
    s.add_dependency(%q<rails>, [">= 3.0.3"])
  end
end

