module Jpmobile::Mobile
  # 携帯電話の抽象クラス。
  class AbstractMobile
    self.@_user_agent_regexp: Regexp?

    @env: Hash[String, untyped]

    @request: untyped

    @_variants: Array[String]?

    # 対応するuser-agentの正規表現
    USER_AGENT_REGEXP: nil

    def initialize: (Hash[String, untyped] env, untyped request) -> void

    # クッキーをサポートしているか。
    def supports_cookie?: () -> bool

    # smartphone かどうか
    def smart_phone?: () -> bool

    # tablet かどうか
    def tablet?: () -> bool

    def default_charset: () -> String

    # for view selector
    def variants: () -> Array[String]?

    # リクエストがこのクラスに属するか調べる
    def self.check_carrier: (Hash[String, untyped] env) -> MatchData?

    def self.user_agent_regexp: () -> Regexp?

    def self.add_user_agent_regexp: (Regexp regexp) -> Regexp

    # Client Hints でリクエストがこのクラスに属するか調べる
    def self.check_client_hints: (Hash[String, untyped] env) -> String?

    def self.carrier: (Hash[String, untyped] env) -> AbstractMobile?

    # Dynamically defined carrier check methods
    def iphone?: () -> bool
    def android?: () -> bool
    def windowsphone?: () -> bool
    def blackberry?: () -> bool
    def ipad?: () -> bool
    def androidtablet?: () -> bool

    private

    # リクエストのパラメータ。
    def params: () -> Hash[String | Symbol, untyped]
  end
end
