# =Willcom携帯電話
module Jpmobile::Mobile
  # ==Willcom携帯電話
  # Ddipocketのスーパクラス。
  class Willcom < AbstractMobile
    @__position: untyped

    # 対応するUser-Agentの正規表現
    USER_AGENT_REGEXP: ::Regexp

    # 対応するメールアドレスの正規表現
    MAIL_ADDRESS_REGEXP: ::Regexp

    # 位置情報があれば Position のインスタンスを返す。無ければ +nil+ を返す。
    def position: () -> untyped

    # cookieに対応しているか？
    def supports_cookie?: () -> true
  end
end
