module Jpmobile
  class Configuration
    @fallback_view_selector: bool

    include Singleton

    attr_accessor fallback_view_selector: bool

    def initialize: () -> void

    module RailsConfiguration
      @jpmobile: Jpmobile::Configuration?

      def jpmobile: () -> Jpmobile::Configuration
    end
  end
end
