module Jpmobile
  class TemplateDetails < ActionView::TemplateDetails
    @mobile: untyped

    def initialize: (untyped locale, untyped handler, untyped format, untyped variant, untyped mobile) -> void

    def matches?: (untyped requested) -> untyped

    def sort_key_for: (untyped requested) -> ::Array[untyped]
  end
end
