module Jpmobile
  class Filter
    @app: untyped

    def initialize: (untyped app) -> void

    def call: (Hash[String, untyped] env) -> [Integer, Hash[String, untyped], untyped]

    private

    def response_to_body: (untyped response) -> String
  end
end
