module Jpmobile
  class Filter
    @app: untyped

    def initialize: (untyped app) -> void

    def call: (untyped env) -> untyped

    private

    def response_to_body: (untyped response) -> untyped
  end
end
