# UserAgent または Client Hints から生成すべき class 名を判定する
module Jpmobile
  class MobileCarrier
    # Client Hints を要求するレスポンスヘッダー
    ACCEPT_CLIENT_HINTS: String

    @app: untyped

    def initialize: (untyped app) -> void

    def call: (Hash[String, untyped] env) -> [Integer, Hash[String, untyped], untyped]
  end
end

class Rack::Request
  include ::Jpmobile::RequestWithMobile
end
