# リクエストパラメータの変換
module Jpmobile
  class ParamsFilter
    @app: untyped

    def initialize: (untyped app) -> void

    def call: (Hash[String, untyped] env) -> [Integer, Hash[String, untyped], untyped]

    private

    def to_internal: (String str, Jpmobile::Mobile::AbstractMobile mobile) -> String

    def parse_query: (String str, Jpmobile::Mobile::AbstractMobile mobile) -> String?
  end
end
