source 'http://rubygems.org'

gem 'rails', '~> 3.2.8'

gem 'sqlite3-ruby', :require => 'sqlite3'

gem 'geokit'
gem 'hpricot'

gem 'jquery-rails'

gem 'jpmobile',             :path => '../../../'
gem 'jpmobile-terminfo',    :path => '../../../vendor/jpmobile-terminfo'
gem 'jpmobile-ipaddresses', :path => '../../../vendor/jpmobile-ipaddresses'

# Bundle gems for certain environments:
group :development, :test do
  gem "rspec", ">= 2.8.0"
  gem "rspec-rails", ">= 2.8.0"
  gem 'webrat'
end
